// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StrongNameKeyGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSnCommandPackageString = "bfacae90-6c14-40be-b1de-13ea0fd11be7";
        public const string guidSnCommandPackageCmdSetString = "74650761-c52d-4c48-a3e2-631df1e426e6";
        public const string guidImagesString = "71c2e89d-822c-4e32-94f0-506a89dbc62a";
        public static Guid guidSnCommandPackage = new Guid(guidSnCommandPackageString);
        public static Guid guidSnCommandPackageCmdSet = new Guid(guidSnCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SnCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
